apiVersion: apps/v1
kind: Deployment
metadata:
  name: reventbookings-deployment
  annotations:
    kubernetes.io/change-cause: "Updating docker image from v1 to v2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reventbookings
  template:
    metadata:
      name: myreventbookings
      labels:
        env: prod
        app: reventbookings
        app.kubernetes.io/name: reventbookings
    spec:
      containers:
        - name: reventbookings
          image: txchi/reventbookings:v2
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80	
              
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-lb-service
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-resource-group: "tochi-aks-tf-rg-dev"
# spec:
#   selector:
#     app.kubernetes.io/name: reventbookings
#   ports:
#     - name: reventbookings-app-port
#       protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app: reventbookings
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080


---

# cd
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-lb-service
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: my-lb-service
            port:
              number: 80
        pathType: Exact
